#pragma once
//mario prop
#define MARIO_WALKING_SPEED		0.1f
#define MARIO_RUNNING_SPEED		0.2f

#define MARIO_ACCEL_WALK_X	0.0005f
#define MARIO_ACCEL_RUN_X	0.0006f

#define MARIO_JUMP_SPEED_Y		0.8f
#define MARIO_JUMP_RUN_SPEED_Y	0.9f

#define MARIO_GRAVITY			0.002f

#define GROUND_Y 160.0f

#define MARIO_BIG_BBOX_WIDTH  19
#define MARIO_BIG_BBOX_HEIGHT 28
#define MARIO_BIG_SITTING_BBOX_WIDTH  19
#define MARIO_BIG_SITTING_BBOX_HEIGHT 18

#define MARIO_SIT_HEIGHT_ADJUST ((MARIO_BIG_BBOX_HEIGHT - MARIO_BIG_SITTING_BBOX_HEIGHT) / 2)

#define MARIO_SMALL_BBOX_WIDTH  16
#define MARIO_SMALL_BBOX_HEIGHT 16

#define ZONE 5
#define MARIO_JUMP_DEFLECT_SPEED 0.4f
#define MARIO_RUN_DEFLECT_SPEED 0.4f

#define MARIO_UNTOUCHABLE_TIME 2500

//state syntax 1 + 9xx
#define STATE_MARIO_IDLE 1901
#define STATE_MARIO_WALK 1902
#define STATE_MARIO_RUN 1903
#define STATE_MARIO_JUMP 1904
#define STATE_MARIO_SIT 1905
#define STATE_MARIO_DIE 1906
#define STATE_MARIO_RELEASE_JUMP 1907
#define STATE_MARIO_RELEASE_SIT 1908

//small syntax 1 + 0xx
#define ID_SMALL_MARIO_ANI_IDLE 1000
#define ID_SMALL_MARIO_ANI_WALK 1001
#define ID_SMALL_MARIO_ANI_JUMP_WALK 1002
#define ID_SMALL_MARIO_ANI_RUN 1003
#define ID_SMALL_MARIO_ANI_SIT 1004
#define ID_SMALL_MARIO_ANI_BRACE 1005
#define ID_SMALL_MARIO_ANI_DIE 1006
#define ID_SMALL_MARIO_ANI_JUMP_RUN 1007

//big syntax 1 + 1xx
#define ID_BIG_MARIO_ANI_IDLE 1100
#define ID_BIG_MARIO_ANI_WALK 1101
#define ID_BIG_MARIO_ANI_JUMP_WALK 1102
#define ID_BIG_MARIO_ANI_RUN 1103
#define ID_BIG_MARIO_ANI_SIT 1104
#define ID_BIG_MARIO_ANI_BRACE 1105
#define ID_BIG_MARIO_ANI_JUMP_RUN 1106

//super syntax 1 + 2xx
#define ID_SUPER_MARIO_ANI_IDLE 1200
#define ID_SUPER_MARIO_ANI_WALK 1201
#define ID_SUPER_MARIO_ANI_JUMP 1202
#define ID_SUPER_MARIO_ANI_RUN 1203
#define ID_SUPER_MARIO_ANI_SIT 1204
#define ID_SUPER_MARIO_ANI_BRACE 1205

//level
#define LEVEL_SMALL "small"
#define LEVEL_BIG "big"
#define LEVEL_SUPER "supper"

//direction
#define DIRECTION_LEFT 1
#define DIRECTION_RIGHT -1