#pragma once
#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_KOOPAS	3
#define OBJECT_TYPE_COIN 4
#define OBJECT_TYPE_PLATFORM 5
#define OBJECT_TYPE_BG 6
#define OBJECT_TYPE_CAM 7
#define OBJECT_TYPE_BRICK_QUESTION 8
#define OBJECT_TYPE_BIG_BRICK 9
#define OBJECT_TYPE_ITEM 10
#define OBJECT_TYPE_KOOPAS_PARA_TROPA 11
#define OBJECT_TYPE_PARA_GOOMBA 12

#define OBJECT_TYPE_PORTAL	50